In [1]:
from random import shuffle
file_name = 'train_self_original.txt'
cand_list = {}
max_line=None
# Read the file and split into lines
persona = []
dial = []
lock = 0
index_dial = 0
data = {}
count=0
with open(file_name) as fin:
    for i, line in enumerate(fin):
        line=line.strip()
        nid, line = line.split(' ', 1)          
        if(int(nid)==1 and lock==1):
            #print(str(sorted(persona)))
            count+=1
            sorted_per = str(sorted(persona))
            if(sorted_per in data):
                data[sorted_per].append(dial)
            else:
                data[sorted_per] = [dial]
            persona = []
            dial = []
            lock = 0
            index_dial = 0
        lock = 1
        if '\t' in line:
            u, r, _, cand  = line.split('\t')   
            cand = cand.split('|')
            shuffle(cand)
            for c in cand:
                if c in cand_list:
                    pass
                else:
                    cand_list[c] = 1 
            dial.append({"nid":index_dial,"u":u,"r":r,'cand':cand})
            index_dial += 1
        else:
            r=line.split(":")[1][1:-1]
            persona.append(str(r))
        i+=1


In [11]:
#print(len(data["['i like to go hunting', 'i like to remodel homes', 'i like to shoot a bow', 'my favorite holiday is halloween']"]))
print('persona number:',count)
persona_first_count = [eval(k) for k, v in data.items()]

cnt=0
pers = []
for per in persona_first_count:
    if 'i am a mother' in per:
        cnt+=1
        pers.append(per)
        print(per)
cnt

persona number: 8938
['i am a mother', 'i enjoy shopping online', 'i enjoy swimming', 'i read fantasy fiction novels', 'i used to work for monsanto']
['i am a mother', 'i love to read and cook', 'my favorite band is the rolling stones', 'my favorite food is mexican food']
['i am a mother', 'i have two children', 'i have two dogs who are like my babies', 'one child has autism']
['i am a mother', 'i am a nurse at a hospital', 'i love to read and cook', 'my favorite band is the rolling stones', 'my favorite food is mexican food']
['i am a mother', 'i am a wife', 'i live by a lake', 'i love my grandchildren', 'i own a custom upholstery shop']
['i am a mother', 'i feel overweight', 'i like to eat', 'i want to be desired', 'i want to feel pretty']
['i am a mother', 'i have two children', 'i have two dogs who are like my babies', 'i work as a teacher and love my job', 'one child has autism']
['i am a mother', 'i am a nurse at a hospital', 'i love to read and cook', 'my favorite band is the ro

16

In [3]:
len(persona_first_count)

4334

In [16]:


def levenshteinDistance(s1, s2):
    if len(s1) > len(s2):
        s1, s2 = s2, s1

    distances = range(len(s1) + 1)
    for i2, c2 in enumerate(s2):
        distances_ = [i2+1]
        for i1, c1 in enumerate(s1):
            if c1 == c2:
                distances_.append(distances[i1])
            else:
                distances_.append(1 + min((distances[i1], distances[i1 + 1], distances_[-1])))
        distances = distances_
    return distances[-1]


In [ ]:
import numpy as np
import itertools
sentence_count=itertools.chain.from_iterable(persona_first_count)
sentence_list = list(set(sentence_count))

In [5]:
import numpy as np
import itertools
sentence_count=itertools.chain.from_iterable(persona_first_count)
sentence_list = list(set(sentence_count))
map_to_index = {}
for i,sent in enumerate(sentence_list):
    map_to_index[sent] = i
X = np.zeros((len(persona_first_count), len(sentence_list)))
for i, persona in enumerate(persona_first_count):
    for sent in persona:
        j = map_to_index[sent]
        X[i,j]=1
X

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [6]:
from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=1155, random_state=0, verbose=100, max_iter=300).fit(X)
kmeans.labels_

Initialization complete
start iteration
done sorting
end inner loop
Iteration 0, inertia 2632.1571428571633
start iteration
done sorting
end inner loop
Iteration 1, inertia 2622.0238095238296
start iteration
done sorting
end inner loop
Iteration 2, inertia 2619.873809523829
start iteration
done sorting
end inner loop
Iteration 3, inertia 2619.873809523829
center shift 0.000000e+00 within tolerance 9.049671e-08
Initialization complete
start iteration
done sorting
end inner loop
Iteration 0, inertia 2635.754761904777
start iteration
done sorting
end inner loop
Iteration 1, inertia 2618.2880952381106
start iteration
done sorting
end inner loop
Iteration 2, inertia 2615.4214285714434
start iteration
done sorting
end inner loop
Iteration 3, inertia 2615.4214285714434
center shift 0.000000e+00 within tolerance 9.049671e-08
Initialization complete
start iteration
done sorting
end inner loop
Iteration 0, inertia 2632.5511904762043
start iteration
done sorting
end inner loop
Iteration 1, inerti

array([ 20, 146, 813, ..., 505, 502, 470], dtype=int32)

In [8]:
y = kmeans.labels_
len(y)

4334

In [21]:
from sklearn.decomposition import LatentDirichletAllocation
lda = LatentDirichletAllocation(n_components=1155,random_state=0)
lda.fit(X) 


/Users/lin/anaconda/lib/python3.6/site-packages/sklearn/decomposition/online_lda.py:536: DeprecationWarning: The default value for 'learning_method' will be changed from 'online' to 'batch' in the release 0.20. This warning was introduced in 0.18.
  DeprecationWarning)
/Users/lin/anaconda/lib/python3.6/site-packages/sklearn/decomposition/online_lda.py:782: RuntimeWarning: overflow encountered in exp
  return np.exp(-1.0 * perword_bound)


array([[0.0004329, 0.0004329, 0.0004329, ..., 0.0004329, 0.0004329,
        0.0004329],
       [0.0008658, 0.0008658, 0.0008658, ..., 0.0008658, 0.0008658,
        0.0008658]])

In [47]:
result = lda.transform(X)
y = np.argmax(result,axis=1)
result[-1][y[-1]]

0.0008658008658008658

1155

In [9]:
persona_map = {}
for i, persona_index in enumerate(list(y)):
    if persona_index not in persona_map:
        persona_map[persona_index] = []
    persona_map[persona_index].append(persona_first_count[i])

In [34]:
persona_map[1001]

[['every fall i visit my sister in canada',
  'i have four cats',
  'i m a vegetarian',
  'i m afraid of clowns',
  'i take the subway to work everyday'],
 ['every fall i visit my sister in canada',
  'i m a vegetarian',
  'i m afraid of clowns',
  'i take the subway to work everyday']]

In [20]:
levenshteinDistance('i works in mcs', 'i work in mcsa')

2

In [29]:
import pickle
with open('persona_map', 'wb') as f:
    pickle.dump(persona_map, f, protocol=4)

In [ ]:
def read_langs(file_name, cand_list, max_line = None):
    print(("Reading lines from {}".format(file_name)))
    # Read the file and split into lines
    persona = []
    dial = []
    lock = 0
    index_dial = 0
    data = {}
    with open(file_name, encoding='utf-8') as fin:
        for line in fin:
            line=line.strip()
            nid, line = line.split(' ', 1)          
            if(int(nid)==1 and lock==1):
                if(str(sorted(persona)) in data):
                    data[str(sorted(persona))].append(dial)
                else:
                    data[str(sorted(persona))] = [dial]
                persona = []
                dial = []
                lock = 0
                index_dial = 0
            lock = 1
            if '\t' in line:
                u, r, _, cand  = line.split('\t')   
                cand = cand.split('|')
                # shuffle(cand)
                for c in cand:
                    if c in cand_list:
                        pass
                    else:
                        cand_list[c] = 1 
                dial.append({"nid":index_dial,"u":u,"r":r,'cand':cand})
                index_dial += 1
            else:
                r=line.split(":")[1][1:-1]
                persona.append(str(r))      
    return data

In [ ]:
file_train = 'data/ConvAI2/train_self_original.txt'
file_dev = 'data/ConvAI2/valid_self_original.txt'
file_test = 'data/ConvAI2/test_self_original.txt'
cand = {}
train = read_langs(file_train, cand_list=cand, max_line=None)
valid = read_langs(file_dev, cand_list=cand, max_line=None)
test = read_langs(file_test, cand_list=cand, max_line=None)
vocab = Lang()
train = preprocess(train,vocab) #{persona:{dial1:[[context,canditate,answer,persona],[context,canditate,answer,persona]]}, dial2:[[context,canditate,answer,persona],[context,canditate,answer,persona]]}}
valid = preprocess(valid,vocab)
test = preprocess(test,vocab)
train = filter_data(cluster_persona(train,'train'),cut=1)
valid = filter_data(cluster_persona(valid,'valid'),cut=1)
test = filter_data(cluster_persona(test,'test'),cut=1)
print("Vocab_size %s " % vocab.n_words)
dial_num = []
for k, v in train.items():
    dial_num.append(len(v))
print(sum(dial_num)/len(dial_num))
plt.hist(dial_num, color = 'blue', edgecolor = 'black', bins = 30)
plt.title('Histogram of persona_dialog')
plt.xlabel('dialog_num')
plt.ylabel('persona_num')
plt.show()